---

# put MetalLB as peer on host network
- hosts: localhost
  connection: local
  tasks:
    - set_fact:
        metal_lb_prefix: "{{ ansible_default_ipv4.address.split('.')[:3]|join('.') }}"

- hosts: kubeadm_cluster
  gather_facts: yes
  become: yes
  vars:
    # define each NIC for netplan here
    additional_nic:
      ens4:
        addresses: ["{{hostvars['localhost'].metal_lb_prefix}}.{{metal_lb_octet}}/24"]
        dhcp4: false
        gateway4: "{{hostvars['localhost'].metal_lb_prefix}}.1"
        nameservers:
          addresses:
          - "{{hostvars['localhost'].metal_lb_prefix}}.1"
          search:
          - home.lab

  roles:
    - additional-netplan-ip
    - local-etc-hosts
    - kubeadm-prereq
    - docker-containerd
    - kubelet-kubeadm-apt
    - k9s
    - yq
