---
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

- name: prereq packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - curl
    state: present
    update_cache: yes

- name: (DEPRECATED) kubernetes legacy package repositories
  block:
  
    - name: add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    
    - name: add google repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        filename: kubeadm
        update_cache: yes
        mode: 0644
        #validate_certs: no
  when: kubeadm_version <= '1.24'

- name: (NEWER) pkgs.k8s.io package repositories
  block:

    # save ASCII-armored gpg key locally
    - name: get key for pkgs.k8s.io apt repo
      shell:
        cmd: curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_version }}/deb/Release.key -o /usr/share/keyrings/kubernetes-apt-keyring.asc

    - name: chmod of keyring
      command:
        cmd: chmod 0644 /usr/share/keyrings/kubernetes-apt-keyring.asc
    
    # add custom apt repo with 'signed-by' referring to gpg key
    - name: add pkgs.k8s.io apt repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubeadm_version }}/deb/ /
        state: present
        filename: kubernetes
        update_cache: yes
        mode: 0644
        validate_certs: false

  when: kubeadm_version > '1.24'


- name: install kubeadm and kubelet packages
  package:
    name:
      - kubelet={{kubeadm_version}}*
      - kubeadm={{kubeadm_version}}*
      - kubectl={{kubeadm_version}}*
      #- kubelet={{kubeadm_version}}*
      #- kubeadm={{kubeadm_version}}*
      #- kubectl={{kubeadm_version}}*
      # not required
      - kubernetes-cni
    state: present
    update_cache: yes
    allow_downgrades: yes

