---

- name: increase cpu resources for etc
  replace:
    path: /etc/kubernetes/manifests/etcd.yaml
    regexp:  'cpu: 100m' # 100m
    replace: 'cpu: 2000m'
  register: cpu_modification
- debug: msg="{{cpu_modification}}"
- name: increase mem resources for etc
  replace:
    path: /etc/kubernetes/manifests/etcd.yaml
    regexp:  'memory: 100Mi' #100Mi
    replace: 'memory: 2000Mi'
  register: memory_modification
- debug: msg="{{memory_modification}}"

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/
- name: wait for etcd ports to be ready
  wait_for:
    host: 0.0.0.0
    port: 2379
    delay: 10
    timeout: 90
  loop:
    - 2379
    - 2380
  when: cpu_modification.changed or memory_modification.changed

# additional wait for filesystem etcd config changes to be picked up
- pause:
    seconds: 30
  when: cpu_modification.changed or memory_modification.changed

- name: wait for kubectl to be ready
  become_user: ubuntu
  shell: "kubectl wait pods -l component=etcd -n kube-system --for=condition=Ready --timeout=10s"
  retries: 20
  delay: 30
  register: kubectl_etcd_ready
  until: kubectl_etcd_ready.rc==0
